### PR TITLE
Fix import of ctypes.util

### PR DESCRIPTION
**Pull request by AnthonyHorton**
Add missing import of `ctypes.util` that was preventing `load_c_library` from working if the full `path` to the library was not specified.

### CODE REVIEW

**Comment by wtgee** [comment]
@AnthonyHorton Is there a built-in linux library we could use to test this?

**Comment by wtgee** [comment]
I'll check out the failing tests, it's because of the docker image that it is pulling for the tests.

**Comment by AnthonyHorton** [comment]
@wtgee Should be able to load any dynamically linked library that's in the usual places. `libc` is probably a safe bet! I'll add a test.

**Comment by wtgee** [comment]
@AnthonyHorton if you pull down the latest changes the tests should start passing. I was hoping you had "Allow Edits from Maintainers" checked so I could just do it for you (although I've never actually done that).

**Comment by AnthonyHorton** [comment]
@wtgee OK, merged and pushed updates from upstream. Will remember to check "Allow Edits from Maintainers" in future :-)

**Pull request merged**
